// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGZIEvStqj3i5aFs_apNYQOyCIo9ivuI',
    appId: '1:315460001458:web:161de49f7a3980ac6d33ab',
    messagingSenderId: '315460001458',
    projectId: 'transitapp-a4f0d',
    authDomain: 'transitapp-a4f0d.firebaseapp.com',
    storageBucket: 'transitapp-a4f0d.firebasestorage.app',
    measurementId: 'G-RGKFD7MR2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fo--tXL2lhMHzC6y1tq-t_93wrTzOEg',
    appId: '1:315460001458:android:cf19ce72aa7394de6d33ab',
    messagingSenderId: '315460001458',
    projectId: 'transitapp-a4f0d',
    storageBucket: 'transitapp-a4f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM02163hGlhTedfXx3cpct79GO6dH3LKE',
    appId: '1:315460001458:ios:3274df1b62ae716e6d33ab',
    messagingSenderId: '315460001458',
    projectId: 'transitapp-a4f0d',
    storageBucket: 'transitapp-a4f0d.firebasestorage.app',
    iosBundleId: 'com.example.transitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM02163hGlhTedfXx3cpct79GO6dH3LKE',
    appId: '1:315460001458:ios:3274df1b62ae716e6d33ab',
    messagingSenderId: '315460001458',
    projectId: 'transitapp-a4f0d',
    storageBucket: 'transitapp-a4f0d.firebasestorage.app',
    iosBundleId: 'com.example.transitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzGZIEvStqj3i5aFs_apNYQOyCIo9ivuI',
    appId: '1:315460001458:web:28649369194e1f116d33ab',
    messagingSenderId: '315460001458',
    projectId: 'transitapp-a4f0d',
    authDomain: 'transitapp-a4f0d.firebaseapp.com',
    storageBucket: 'transitapp-a4f0d.firebasestorage.app',
    measurementId: 'G-G75PZZLZD6',
  );
}
